import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Coordenadas from "@/components/ui/Coordenadas";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <Coordenadas></Coordenadas>
        {children}
      </body>
    </html>
  );
}
